databaseChangeLog:
  - logicalFilePath: config/liquibase/changes/changelog-0.0.3-create-movie-session-table.yaml

  - changeSet:
      id: 1
      author: mikhail
      comment: "Create MovieSession table"
      changes:
        - createTable:
            tableName: movie_session
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: movie_date
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: created_by
                  type: varchar(100)
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: updated_by
                  type: varchar(100)
              - column:
                  name: movie_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_movie_session_movie
                    references: movie(id)

  - changeSet:
      id: 2
      author: mikhail
      comment: "Add movie session"
      changes:
        - insert:
            tableName: movie_session
            columns:
              - column:
                  name: movie_date
                  value: "2020-01-01 10:10:10"
              - column:
                  name: movie_id
                  value: 1
              - column:
                  name: created_at
                  value: "2020-01-01 09:10:10"
              - column:
                  name: created_by
                  value: mikhail
              - column:
                  name: updated_at
                  value: "2020-01-01 10:10:10"
              - column:
                  name: updated_by
                  value: mikhail