databaseChangeLog:
  - logicalFilePath: config/liquibase/changes/changelog-0.0.2-create-movie-table.yaml
  - changeSet:
     id: 1
     author: mikhail
     comment: "Create movie table"
     changes:
       - createTable:
           tableName: movie
           columns:
             - column:
                 name: id
                 type: BIGINT
                 autoIncrement: true
                 constraints:
                   primaryKey: true
                   nullable: false
             - column:
                 name: name
                 type: varchar(100)
                 constraints:
                   nullable: false
             - column:
                 name: release_year
                 type: BIGINT
                 constraints:
                   nullable: false
             - column:
                 name: producer
                 type: varchar(100)
             - column:
                 name: description
                 type: text
             - column:
                 name: updated_at
                 type: TIMESTAMP
             - column:
                 name: updated_by
                 type: varchar(100)

  - changeSet:
     id: 2
     author: mikhail
     comment: "Add movies"
     changes:
       - insert:
           tableName: movie
           columns:
             - column:
                 name: name
                 value: "Star Wars: The Rise Of Skywalker"
             - column:
                 name: release_year
                 value: 2019
             - column:
                 name: producer
                 value: "J.J. Abrams"
             - column:
                 name: description
                 value: "The surviving members of the resistance face the First Order once again, and the legendary conflict between the Jedi and the Sith reaches its peak bringing the Skywalker saga to its end."
             - column:
                 name: updated_at
                 value: "2020-01-01 10:10:10"
             - column:
                 name: updated_by
                 value: mikhail

