databaseChangeLog:
  - logicalFilePath: config/liquibase/master.yaml
  - changeSet:
      id: 1
      author: mikhail
      comment: "Create table users"
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: surname
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: username
                  type: varchar(50)
                  constraints:
                    unique: true
                    nullable: false
              - column:
                  name: email
                  type: varchar(254)
                  constraints:
                    unique: true
                    nullable: false
              - column:
                  name: password
                  type: varchar(512)
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: updated_by
                  type: varchar(100)

  - changeSet:
      id: 2
      author: mikhail
      comment: "Create movie table"
      changes:
        - createTable:
            tableName: movie
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: release_year
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: producer
                  type: varchar(100)
              - column:
                  name: description
                  type: varchar(8192)
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: updated_by
                  type: varchar(100)


  - changeSet:
      id: 3
      author: mikhail
      comment: "Create MovieSession table"
      changes:
        - createTable:
            tableName: movie_session
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: movie_date
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: updated_by
                  type: varchar(100)
              - column:
                  name: movie_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_movie_session_movie
                    references: movie(id)


  - changeSet:
      id: 4
      author: mikhail
      comment: "Create Ticket table"
      changes:
        - createTable:
            tableName: ticket
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: row
                  type: BIGINT
              - column:
                  name: place
                  type: BIGINT
              - column:
                  name: updated_at
                  type: TIMESTAMP
              - column:
                  name: updated_by
                  type: varchar(100)


  - changeSet:
      id: 5
      author: mikhail
      comment: "Add movies"
      changes:
        -insert:
          tableName: movie
          columns:
            - column:
                name: name
                value: "Star Wars: The Rise Of Skywalker"
            - column:
                name: release_year
                value: 2019
            - column:
                name: producer
                value: "J.J. Abrams"
            - column:
                name: decription
                value: "The surviving members of the resistance face the First Order once again, and the legendary conflict between the Jedi and the Sith reaches its peak bringing the Skywalker saga to its end."
