spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: cinema_user
    password: cinema_pass
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    show-sql: true
    properties:
      #      hibernate.generate_statistics: true
      #      hibernate.format_sql: true
      hibernate:
        ddl-auto: none
        connection.provider_disables_autocommit: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.time_zone: UTC
        cache.use_second_level_cache: false
        cache.use_query_cache: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/master.yaml

keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://127.0.0.1:8180/auth
  ssl-required: external
  resource: login-app
  credentials.secret: 11111111-1111-1111-1111-111111111111
  use-resource-role-mappings: true

server:
  port: 8081