version: "3.3"
services:
  cinema-postgresql:
    image: postgres:11.6
    volumes:
      - ./postgres/datadir:/var/lib/postgresql/data
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: "admin"
#      KEYCLOAL_IMPORT: '/tmp/realm.json'
      DB_VENDOR: 'POSTGRES'
      DB_ADDR: 'postgres'
      DB_DATABASE: 'cinema_db'
      DB_USER: 'cinema_user'
      DB_PASSWORD: 'cinema_pass'

#    volumes:
#      - ${KEYCLOAK_REALM_JSON}:/tmp/realm.json
    ports:
      - 8081:8081
    depends_on:
      - cinema-postgresql
