version: '3.6'
services:
  postgres:
    restart: always
    image: 'postgres:11.5'
    secrets:
      - source: database initialization
        target: "/docker-entrypoint-initdb.d/create-db.sh"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSRGRES_PASSWORD: 'cinema'
      POSTGRES_DB: 'cinema'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
